version: '3'

services:
  distro:
    image: alpine:latest
    restart: always
    container_name: Custom_alpine

  database:
    image: postgres:12.2-alpine
    restart: always
    container_name: postgres_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: redhat
    volumes:
      - ../dump:/tmp

  web:
    image: nginx
    restart: always
    container_name: nginx_web
    ports:
      - 8082:80
    volumes:
      - ./mysite/.template:/etc/nginx/conf.d/mysite.template
    environment:
      NGINX_HOST: sample.com
      NGINX_PORT: 80
    links:
      - database:db
      - distro

volumes:
  data:
    external: true



